# flake8: noqa
# Generated by Django 3.2.16 on 2023-09-10 08:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230907_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#675858', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет тега'),
        ),
    ]
